# Generated by Django 4.2.1 on 2023-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verifyphonenumber_user_phone_number_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyphonenumber',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
