# Generated by Django 4.2.1 on 2023-05-22 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_verifyphonenumber_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifyphonenumber",
            name="OTP_for",
            field=models.CharField(
                choices=[("N", "NEW_ACCOUNT")], default="N", max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="verifyphonenumber",
            name="expire_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
